//! Cross-language wire-format contract.
//!
//! The Python SDK builds request bodies by hand rather than from generated code, so nothing
//! but a test stops the two sides drifting apart. This deserializes a request the SDK
//! actually produced (`tests/contract/sdk_wire_request.json`, regenerated by
//! `make contract-fixtures`) into the Rust types Core uses.
//!
//! A field the SDK renames, drops or mistypes shows up here as a parse failure at build time
//! rather than as a 400 in production — or, worse, as a field Core silently defaults while
//! the SDK believes it was sent.

use std::path::PathBuf;
use vigil_protocol::action::Action;
use vigil_protocol::trust::TrustLevel;
use vigil_protocol::ActionRequest;

fn fixture() -> String {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .map(|p| p.join("tests/contract/sdk_wire_request.json"))
        .expect("workspace root");
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("SDK wire fixture missing at {}: {e}", path.display()))
}

#[test]
fn a_request_built_by_the_python_sdk_deserializes_into_the_core_types() {
    let request: ActionRequest =
        serde_json::from_str(&fixture()).expect("SDK wire format must parse in Core");

    assert_eq!(request.schema_version, vigil_protocol::SCHEMA_VERSION);
    assert_eq!(request.tenant_id.as_str(), "acme");
    assert_eq!(request.agent_id.as_str(), "customer-support-assistant");
    assert!(request.principal.mfa);
    assert!(request.principal.has_role("support-agent"));

    // The SDK's claimed identity survives; its claim to have been *verified* does not.
    // The fixture asserts `"verified": true` on the wire, and the type refuses to honour it
    // — verification can only be established by the API layer from the transport.
    let workload = request
        .workload_identity
        .as_ref()
        .expect("workload identity");
    assert_eq!(workload.id, "spiffe://vigil.test/ns/agents/sa/support");
    assert!(
        !workload.verified,
        "a client-supplied `verified` flag must not survive the wire boundary"
    );

    match &request.action {
        Action::ToolCall(t) => {
            assert_eq!(t.name, "send_email");
            assert_eq!(t.operation.as_deref(), Some("send"));
            assert_eq!(t.arguments["to"], "cfo@acme.example");
        }
        other => panic!("expected a tool call, got {other:?}"),
    }
}

#[test]
fn the_sdks_provenance_and_reasoning_fields_survive_the_boundary() {
    let request: ActionRequest = serde_json::from_str(&fixture()).expect("parses");

    // Observable reasoning telemetry is optional but must round-trip when present.
    assert_eq!(
        request.context.declared_objective.as_deref(),
        Some("answer the customer's billing question")
    );
    assert_eq!(request.context.step, 3);

    let source = request
        .context
        .influencing_sources
        .first()
        .expect("influencing source");
    assert_eq!(source.trust_level, TrustLevel::WebUntrusted);
    assert!(!source.trust_level.carries_instruction_authority());
}

#[test]
fn the_request_passes_the_same_validation_core_applies() {
    let request: ActionRequest = serde_json::from_str(&fixture()).expect("parses");
    request
        .validate()
        .expect("an SDK-produced request must satisfy Core's structural checks");
    // And it hashes, which is what every binding depends on.
    assert!(request.action_hash().is_ok());
}

#[test]
fn a_request_whose_tenant_disagrees_with_its_principal_is_rejected() {
    // The SDK rejects this client-side too; this proves Core does not rely on that.
    let mut raw: serde_json::Value = serde_json::from_str(&fixture()).expect("parses");
    raw["tenant_id"] = serde_json::json!("other-corp");
    let request: ActionRequest = serde_json::from_value(raw).expect("parses");
    assert!(request.validate().is_err());
}
