#!/usr/bin/env python3
"""Generate the reviewable source-evidence inventory used by VIGIL's public docs.

This script counts committed declarations, not successful executions. GitHub Actions is the
source of truth for whether those declarations compile and pass on each supported runner.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MARKDOWN = ROOT / "docs" / "generated" / "evidence.md"
JSON = ROOT / "docs" / "generated" / "evidence.json"
README = ROOT / "README.md"


def source_files(suffix: str) -> list[Path]:
    excluded = {".git", ".venv", "target"}
    return [
        path
        for path in ROOT.rglob(f"*{suffix}")
        if not excluded.intersection(path.relative_to(ROOT).parts)
    ]


def occurrences(paths: list[Path], pattern: str) -> int:
    regex = re.compile(pattern, re.MULTILINE)
    return sum(len(regex.findall(path.read_text(encoding="utf-8"))) for path in paths)


def inventory() -> dict[str, int]:
    rust = source_files(".rs")
    swift = source_files(".swift")
    python = source_files(".py")
    crate_dirs = sorted((ROOT / "crates").glob("*/Cargo.toml"))
    roots = [
        root
        for manifest in crate_dirs
        for root in (manifest.parent / "src" / "lib.rs", manifest.parent / "src" / "main.rs")
        if root.exists()
    ]
    adversarial = ROOT / "crates" / "vigil-cli" / "tests" / "adversarial.rs"
    release_gates = ROOT / "crates" / "vigil-cli" / "tests" / "release_gates.rs"
    fuzz_manifest = (ROOT / "fuzz" / "Cargo.toml").read_text(encoding="utf-8")

    return {
        "rust_test_entry_points": occurrences(
            rust, r"^\s*#\[(?:tokio::)?test(?:\([^\]]*\))?\]"
        ),
        "swift_test_entry_points": occurrences(swift, r"^\s*func\s+test\w+\s*\(")
        + occurrences(swift, r"^\s*@Test\b"),
        "python_test_functions": occurrences(python, r"^def\s+test_\w+\s*\("),
        "adversarial_harness_tests": occurrences(
            [adversarial], r"^\s*#\[test\]"
        ),
        "named_attack_paths": occurrences([adversarial], r"^fn\s+attack_\w+\s*\("),
        "release_security_gates": occurrences(
            [release_gates], r"^\s*#\[test\]"
        ),
        "fuzz_targets": len(re.findall(r"^\[\[bin\]\]", fuzz_manifest, re.MULTILINE)),
        "architecture_decisions": len(list((ROOT / "docs" / "adr").glob("[0-9]*.md"))),
        "workspace_crates": len(crate_dirs),
        "unsafe_code_constructs": occurrences(
            rust, r"\bunsafe\s+(?:fn\b|impl\b|trait\b|extern\b|\{)"
        ),
        "crates_forbidding_unsafe": sum(
            "#![forbid(unsafe_code)]" in root.read_text(encoding="utf-8") for root in roots
        ),
    }


def render_md(values: dict[str, int]) -> str:
    rows = [
        ("Rust test entry points", "rust_test_entry_points"),
        ("Swift test entry points", "swift_test_entry_points"),
        ("Python test functions", "python_test_functions"),
        ("Adversarial harness tests", "adversarial_harness_tests"),
        ("Named attack paths", "named_attack_paths"),
        ("Release security gates", "release_security_gates"),
        ("Fuzz targets", "fuzz_targets"),
        ("Architecture decision records", "architecture_decisions"),
        ("Workspace crates", "workspace_crates"),
        ("Unsafe Rust constructs", "unsafe_code_constructs"),
        ("Crates forbidding unsafe code", "crates_forbidding_unsafe"),
    ]
    table = "\n".join(f"| {label} | {values[key]} |" for label, key in rows)
    return f"""# Generated evidence inventory

> Generated by `python3 scripts/generate_evidence.py`. Do not edit by hand.

These values are declarations found in the committed source tree. They are not a claim that
every test passed in the latest run; the [CI workflow](../../.github/workflows/ci.yml) carries
that execution evidence. Parameterized test cases can produce more runtime cases than the source
function count.

| Evidence | Count |
|---|---:|
{table}

The counting rules live beside the claim in `scripts/generate_evidence.py`, and CI fails when
this file or its JSON companion is stale.
"""


def render_readme_fragment(values: dict[str, int]) -> str:
    rust = values["rust_test_entry_points"]
    swift = values["swift_test_entry_points"]
    adversarial = values["adversarial_harness_tests"]
    fuzz = values["fuzz_targets"]
    adrs = values["architecture_decisions"]
    crates = values["workspace_crates"]
    unsafe = values["unsafe_code_constructs"]
    unsafe_label = "zero" if unsafe == 0 else str(unsafe)
    return f"""<!-- evidence:start -->
The committed inventory currently finds **{rust} Rust test entry points, {swift} Swift test entry
points, {adversarial} adversarial harness tests, {fuzz} fuzz targets, {adrs} ADRs, {crates} workspace
crates, and {unsafe_label} unsafe Rust constructs**. Those are source declarations, not a
hand-maintained “passing” count;
CI supplies execution status and rejects a stale inventory.
<!-- evidence:end -->"""


def write_or_check(path: Path, expected: str, check: bool) -> bool:
    if check:
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual != expected:
            print(f"stale generated evidence: {path.relative_to(ROOT)}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if committed evidence is stale"
    )
    args = parser.parse_args()
    values = inventory()
    markdown = render_md(values)
    serialized = json.dumps(values, indent=2, sort_keys=True) + "\n"
    ok = write_or_check(MARKDOWN, markdown, args.check)
    ok = write_or_check(JSON, serialized, args.check) and ok
    readme = README.read_text(encoding="utf-8")
    fragment = render_readme_fragment(values)
    pattern = re.compile(
        r"<!-- evidence:start -->.*?<!-- evidence:end -->", re.DOTALL
    )
    updated, replacements = pattern.subn(fragment, readme)
    if replacements != 1:
        print("README must contain exactly one generated evidence block", file=sys.stderr)
        ok = False
    elif args.check and updated != readme:
        print("stale generated evidence: README.md", file=sys.stderr)
        ok = False
    elif not args.check:
        README.write_text(updated, encoding="utf-8")
    if ok:
        verb = "verified" if args.check else "generated"
        print(f"{verb} {MARKDOWN.relative_to(ROOT)} and {JSON.relative_to(ROOT)}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
